version: "3.9"

services:

  postgres:

    image: postgres:17

    container_name: enterprise_postgres

    restart: always

    environment:
      POSTGRES_DB: enterprise_sales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:

    build: .

    depends_on:
      - postgres

    env_file:
      - .env

volumes:
  postgres_data: